name: Build Android TWA

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Install Bubblewrap
        run: npm install -g @bubblewrap/cli

      - name: Init TWA (auto-confirm)
        run: |
          echo "y" | bubblewrap init --manifest=manifest.json

      - name: Build TWA Project
        run: bubblewrap build

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Decrypt Release Keystore
        if: ${{ secrets.KEYSTORE_BASE64 != '' }}
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > keystore.jks

      - name: Build Release APK
        env:
          SIGNING_STORE_FILE: ${{ github.workspace }}/keystore.jks
          SIGNING_STORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          SIGNING_KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: ./gradlew assembleRelease

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: CV_AP_APK
          path: app/build/outputs/apk/release/*.apk

      - name: Upload AAB
        uses: actions/upload-artifact@v4
        with:
          name: CV_AP_AAB
          path: app/build/outputs/bundle/release/*.aab
